Update patch set 1
Patch Set 1: Code-Review-2

Travis CI reports failing spec test at https://travis-ci.org/simp/rubygem-simp-rake-helpers/pull_requests (Previous commits passed the same test).  

The Travis CI tests fail because `rpmspec` is missing: https://travis-ci.org/simp/rubygem-simp-rake-helpers/jobs/105062125#L206

It should be possible to get `rpmspec` by adding this to the .travis.yml:

```yaml
sudo: required
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y rpm
```

However, the Simp::RPM.get_info spec tests will fail even with `rpmspec`:

```
Simp::RPM
error: line 7: Empty tag: URL:
  #initialize
    initializes (smoke test)
  .get_info
error: line 7: Empty tag: URL:
    extracts correct information from a .spec file (FAILED - 1)
```

Patch-set: 1
Reviewer: Chris Tessmer <1005143@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=-2