Update patch set 2
Patch Set 2: Code-Review-2 Verified-1

Looks like `build.rb` needs an update to use R10K::Git::ShellGit::ThinRepository#each_module:

```
# from a bundle exec rake build:auto run:
--------------------------------------------------------------------------------
#### Checking out subrepositories using method 'tracking'
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
#### Running bundler in all repos
     (Disable with `SIMP_BUILD_bundle=no`)
--------------------------------------------------------------------------------
rake aborted!
NameError: uninitialized constant Simp::Rake::Build::Build::FakeLibrarian
/home/chris/.rvm/gems/ruby-1.9.3-p551/gems/simp-rake-helpers-1.4.0/lib/simp/rake/build/build.rb:43:in `block (2 levels) in define_tasks'
/home/chris/.rvm/gems/ruby-1.9.3-p551/gems/simp-rake-helpers-1.4.0/lib/simp/rake/build/auto.rb:150:in `block (2 levels) in define'
/home/chris/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/chris/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

Patch-set: 2
Label: Code-Review=-2
Label: Verified=-1